version: "3.8"

services:
  postgres_user:
    image: postgres:latest
    container_name: postgres_user_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Quantum9963
      POSTGRES_DB: user_db
    volumes:
      - shared-postgres-data:/var/lib/postgresql/data
    networks:
      - my_network

  postgres_product:
    image: postgres:latest
    container_name: postgres_product_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Quantum9963
      POSTGRES_DB: product_db
    volumes:
      - shared-postgres-data:/var/lib/postgresql/data
    networks:
      - my_network

  user-service:
    build: ./userservice
    container_name: user-service
    depends_on:
      - postgres_user
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_user:5432/user_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Quantum9963
    ports:
      - "8080:8080"
    networks:
      - my_network

  product-service:
    build: ./productservice
    container_name: product-service
    depends_on:
      - postgres_product
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_product:5432/product_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Quantum9963
    ports:
      - "8081:8081"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  shared-postgres-data:
